# script to merge histograms generated by analysis train into one file per run

import os
import phadd

RUNPERIOD = "RunPeriod-2016-02"
VERSION = "ver04"
BASEDIR = "/cache/halld/%s/analysis/%s/hists"%(RUNPERIOD,VERSION)
merged_dir = "%s/%s"%(BASEDIR,"merged")

# find the list of runs for this train launch
root_file_dirs = [ d for d in os.listdir(BASEDIR) if len(d)==6 ]

# save merged files into separate directories
os.system("mkdir -p "+merged_dir)

for rundir in root_file_dirs:
    try:
        run = int(rundir)
    except:
        continue
    print "merging directory %s ..."%rundir
    merged_file = "%s/hd_root_%s.root"%(merged_dir,rundir)
    if os.path.isfile(merged_file):
        print "  skipping ..."
        continue
    root_files = [ BASEDIR+"/"+rundir+"/"+f for f in os.listdir(BASEDIR+"/"+rundir) if f[-5:]==".root" ]

    #hadder = phadd.phadd(merged_file, sorted(root_files), " -k -v 0 ", 6, 10)
    hadder = phadd.phadd(merged_file, sorted(root_files), " -k ", 6, 10)
    hadder.Add()
