#
# Plan: make a log entry to save the rootspy plots after the first X events of run Y
#if dictlist['HD:coda:daq:status']['mean'] != 2 :   # daq status - HD:coda:daq:status = 2 for 'go'

# 
# Use these epics PVs: HD:coda:EventNumber HD:coda:daq:run_number
# 
# Have this code run just once, looking at the last minute.
# Call it repeatedly via cron.
#
# Write run number into a file, so that further warnings can be suppressed for a while.
#

import os
from datetime import datetime,timedelta
import time

testing = False

events_required = 50000000 # 50M

sleeptime = 60  #seconds to wait before trying mya again after an outage

# warning message suppression times
outage_warning_suppression_time = timedelta(minutes=30)
err_warning_suppression_time = timedelta(minutes=240)

# temp output filenames
epicsfile = '_epics.txt'             # mystats printout
runloggedfile = '_runlogged.txt'         # last run for which plots were saved
warningfile = '_warning.txt'         # warning message text eg if epics reports N/A

# problem logging output filenames
errfile = '_epics_err_warning.txt'           # time of last mystats error warning
outagefile = '_epics_outage_warning.txt'     # time of last mystats outage warning

#list of plots to include
include_histos = ' -H //BCAL_occupancy -H //CDC_occupancy -H //DIRC_occupancy -H //ECAL_occupancy -H //FCAL_occupancy -H //FDC_occupancy'
include_histos += ' -H //FDC_P1_pseudo_occupancy  -H //FDC_P2_pseudo_occupancy  -H //FDC_P3_pseudo_occupancy  -H //FDC_P4_pseudo_occupancy -H //PS_occupancy -H //RF_TPOL_occupancy -H //ST_occupancy -H //TAGGER_occupancy -H //TOF_occupancy'
include_histos += ' -H //HistMacro_Beam -H //HistMacro_Kinematics -H //HistMacro_NumHighLevelObjects -H //HistMacro_OnlineRF -H //HistMacro_PID -H //HistMacro_Trigger -H //HistMacro_Trigger_EnergyCorrelation -H //HistMacro_Vertex'
include_histos += ' -H //HistMacro_bad_hits -H //HistMacro_fa125_itrig -H //HistMacro_fa125_temp'


#-----------------------------------------------------------------------------------

def run_mystats(epicsfile) :
    
    pvlist = 'HD:coda:daq:status,HD:coda:daq:run_number,HD:coda:EventNumber'

    if os.path.exists(epicsfile):
        os.remove(epicsfile)

    cmd = "myStats -b -10s -e 0 -u -f " + epicsfile + " -l " + pvlist

    os.system(cmd)
    
    return

#-----------------------------------------------------------------------------------

def check_output_exists(thisfile):
    
    if os.path.exists(thisfile):
        return True
    
    timeformat = "%Y-%m-%d %H:%M:%S"

    time_since_warning = find_time_since_warning(errfile)
    
    if time_since_warning > err_warning_suppression_time :
        issue_warning('no_epics_output')
        record_time(errfile)
    else :
        if testing:
            print('EPICS archive access error warning issued recently')

    return False


#-----------------------------------------------------------------------------------

def read_mystats(epicsfile) :

    f = open(epicsfile,'r')
    lines = f.readlines()
    f.close()

    dictlist = {}    
    # Name     Min   Mean   Max   Sigma
    
    for line in lines:
 
        things = line.strip().split(" ")
        pvname = things[0]
            
        if things[3] == 'N/A' :
            max = -1
        elif things[3] == '<undefined>' :
            max = -1
        else :
            max = things[3]        

        if things[4] == 'N/A' :
            sigma = -1
        elif things[4] == '<undefined>' :
            sigma = -1
        else :
            sigma = float(things[4])        

        dict = {pvname : { "max":max, "sigma":sigma}}
        dictlist.update(dict)
        
    return dictlist


#-----------------------------------------------------------------------------------    


def issue_warning(pv) :

    # See https://logbooks.jlab.org/content/api-authentication
    # Need this set: export JAVA_HOME=/gapps/Java/jdk/23.0.1/x64/jdk23.0.1/
    
    os.putenv('JAVA_HOME','/gapps/Java/jdk/23.0.1/x64/jdk23.0.1/')  # needed to make the log entry


    f = open(warningfile,'w')
    
    if pv == 'no_epics_output' :
        title = 'Cron script could not access EPICS archive'
        f.write(title)
    else :
        title = 'DAQ EPICS PVs unavailable in MYA'
        f.write("The following EPICS PVs were recently unavailable in MYA:\n")
        f.write(pv)

     
    import platform
    f.write("\n\n")
    
    f.write("This message was generated by Naomi's save_plots script, running as a cron job on " + platform.node() + "\n")
    f.close()

    cmd = '/site/ace/certified/apps/bin/logentry -l HDLOG -g Autolog -t "' + title + '" -b ' + warningfile + ' -n njarvis@jlab.org'


    if testing:
        print(cmd)
        print('logbook entry deactivated')
    else :
        os.system(cmd)
    return


#-----------------------------------------------------------------------------------

def find_time_since_warning(filename) :

    timeformat = "%Y-%m-%d %H:%M:%S"

    if not os.path.exists(filename):
        time_since_warning = timedelta(days=1000)     # no previous warnings were made 
    else :
        lastwarning = read_time(filename)
        time_since_warning = datetime.now() - datetime.strptime(lastwarning,timeformat)   #this is a timedelta
    return time_since_warning

#-----------------------------------------------------------------------------------

def record_time(filename) :

    timeformat = "%Y-%m-%d %H:%M:%S"
    
    f = open(filename,'w')
    f.write(datetime.now().strftime(timeformat))
    f.close()       
    return

#-----------------------------------------------------------------------------------

def read_time(filename) :

    f = open(filename,'r')
    time_recorded = f.readline()
    f.close()

    return time_recorded



#-----------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------
#------ main -----------------------------------------------------------------------


run_mystats(epicsfile)


allok = check_output_exists(epicsfile)   # this issues a warning if the file is not there

if not allok:
    exit('not ok')

dictlist = read_mystats(epicsfile)   

# the dictlist is a list of dicts like 
# eg {'IBCAD00CRCUR6': {'mean': 0.275, 'sigma': 0.641775}}
# invalid mean or sigma, eg 'N/A', are set to -1

# check for epics outages. 

outages = ""
outages2 = ""

for dict in dictlist:
    if float(dictlist[dict]['max']) < 0  : 
        outages = outages + dict + " "
    #print(dict, dictlist[dict])
    
if outages != "" :

    # make a second attempt at getting good epics data 

    time.sleep(sleeptime)

    run_mystats(epicsfile)
    allok2 = check_output_exists(epicsfile)   # this issues a warning if the file is not there

    if not allok2:
        exit('not ok')

    dictlist = read_mystats(epicsfile)   

    for dict in dictlist:
        if float(dictlist[dict]['max']) < 0  : 
            outages2 = outages2 + dict + " "
            

if outages2 != "" :

    time_since_warning = find_time_since_warning(outagefile)
    
    if time_since_warning > outage_warning_suppression_time :
        issue_warning(outages)
        record_time(outagefile)
    else :
        if testing:
            print('EPICS outage warning issued recently')
    exit()

# no outages were found, so check other data

#if dictlist['HD:coda:daq:status']['mean'] != 2 :   # daq status - HD:coda:daq:status = 2 for 'go'
#    if testing:
#        print('DAQ is not running')
#    exit()

line = 'xxx'
if os.path.exists(runloggedfile) :
    f = open(runloggedfile,'r')
    line = f.readline()
    f.close()

current_run = dictlist['HD:coda:daq:run_number']['max'] 
current_events = float(dictlist['HD:coda:EventNumber']['max'])

if current_run == '0':  # daq is not running
    exit()

if current_run in line :
    if testing:
        print('Already logged plots for current run, ' + current_run)
        exit()
    exit()

if current_events < events_required :
    if testing:
        print('Insufficient events ' + str(events_required))
    exit()

if testing:
    print('making log entry')

    # See https://logbooks.jlab.org/content/api-authentication
    # Need this set: export JAVA_HOME=/gapps/Java/jdk/23.0.1/x64/jdk23.0.1/
    
os.putenv('JAVA_HOME','/gapps/Java/jdk/23.0.1/x64/jdk23.0.1/')  # needed to make the log entry

cmd = '/gapps/RootSpy/dev/Linux_RHEL9-x86_64-gcc11.5.0/bin/RSelog -L HDMONITOR -R ' + current_run + include_histos

if testing:
    print(cmd)
    print('logbook entry deactivated')
else :
    os.system(cmd)

f = open(runloggedfile,'w')
f.write(current_run)
f.close()
