// purpose: find relative timing offsets between fADC and TDC
//          determine timing offsets for fADC times for all PMTs based on the 
//          time difference between fADC and TDC times.
//          The histograms dtXXX display the fADCtime - TDCtime distribution this should be at zero
//          for fully calibrated fADC and TDC times. Any non zero value indicates the fADC time to be
//          off and represents the correction to the individual fADC offsets in ccdb.
//
//          Also at the same stage determine offset between TDC TOF time and RF time
//          the difference should be at zero howerver if it is not at zero means
//          the global TDC time offset is wrong and needs to be corrected.
//          us the histogram DeltaTVsP_Pi+ in hd_root.root generated by the monitoring_hists plugin
//          project xbins 48-52 to vertical axis and find maximum this should be at zero. Any non zero
//          value indicates that the global TDC offset is off by that much.
//
//          the timing corrections for fADC and TDC times are applied in DTOFHit_factory as follows:
//          fADC_time = fADC_rawtime * ADCscale2ns + t_base - channel_offset
//                      t_base :        is a global offset (same for all PMTs)
//                      channel_offset: is an individual offset for each PMT
//
//          TDC_time = TDC_rawtime * convert2ns + t_base_tdc - channel_offset - walkcorr
//                     t_base_tdc :     is a globel time offset (same for all PMTs)
//                     channel_offset:  is an individual offset for each PMT
//                     walkcorr:        is an individual offset for each PMT dependent of signal amplitude
//
//
//          Changing the global TDC time offset will alter the result for fADC_time - TDC_time and
//          can be absorbed into the fADC global time offset by changing it by the same amount. In this way
//          the time difference between fADC and TDC time would not be affected.
//

int DEBUG = 0;
int GenNewParFiles = 1 ;

void getadcoff(int RunNumber){

  double GlobalTDCOffsetCorr = 0;


  // First read hd_root.root and determine correction for global TDC offset
  char rootfnam[128];
  sprintf(rootfnam, "localdir/run%d/hd_root.root",RunNumber);
  TFile *RF1 = new TFile(rootfnam,"READ");
  TH2I *h2d = (TH2I*)RF1->Get("Independent/Hist_DetectorPID/TOF/DeltaTVsP_Pi+");

  TH1D *hproject = h2d->ProjectionY("hproject", 48, 52);
  if (hproject != NULL){

    if (hproject->GetEntries()<100){
      cout<<"Error not enough data for TOF-RF timing offset determination"<<endl;
      return;
    }
    
    double max = hproject->GetBinCenter(hproject->GetMaximumBin());
    double loli = max - 5.*hproject->GetBinWidth(1);
    double hili = max + 5.*hproject->GetBinWidth(1);
    hproject->Fit("gaus","","R", loli, hili);
    TF1 *f1 = hproject->GetFunction("gaus");
    max = f1->GetParameter(1); // This is the correction for the global TDC time offset! It needs to be subracted!
    GlobalTDCOffsetCorr = max;

  } else {
    cout<<"Error finding histogram to get TOF-RF timing offsets"<<endl;
    return;
  }

  if (DEBUG){
    hproject->Draw();
    gPad->SetGrid();
    gPad->Update();
    getchar();
  }

  RF1->Close();

  sprintf(rootfnam, "localdir/run%d/tofhittest.root",RunNumber);

  TFile *RF = new TFile(rootfnam, "READ");

  double POS[176];

  char hnam[128];
  for (int k=0;k<176;k++){
    sprintf(hnam, "dt%03d",k);
    TH2D *h2d = (TH2D*)RF->Get(hnam);
    POS[k] = 0;
    
    if (h2d==NULL){
      cout<<"error no histogram "<<hnam<<endl;
      continue;
    }

    if (h2d->GetEntries()>0){

      TH1D *p1 = (TH1D*)h2d->ProjectionY("p1", 6, h2d->GetXaxis()->GetNbins()-2);
      if (p1){
	double max = p1->GetBinCenter(p1->GetMaximumBin());
	p1->Fit("gaus","","R", max-.25, max+.25);
	TF1 *f1 = p1->GetFunction("gaus");
	POS[k] = f1->GetParameter(1);
	if (DEBUG){
	  p1->Draw();
	  gPad->Update();
	}
      }

    }

  }

  char ofnam[128];
  sprintf(ofnam, "adcoffsets_found_run%d.dat",RunNumber);
  ofstream OF(ofnam);
  
  for (int k=0;k<176;k++){
    
    OF<<POS[k]<<endl;
    
  }
  OF.close();

  sprintf(ofnam, "globaloffset_found_run%d.dat",RunNumber);
  ofstream OF1(ofnam);
  OF1<<GlobalTDCOffsetCorr<<endl;
  OF1.close();
  
  if (GenNewParFiles){

      char cmd[128];
      sprintf(cmd,"ccdb dump /TOF/base_time_offset:%d:default: > base_time_offsets.dat",RunNumber);
      system(cmd);
      
      sprintf(cmd,"ccdb dump /TOF/adc_timing_offsets:%d:default: > adc_timing_offsets.dat",RunNumber);
      system(cmd);
      
      ifstream INF("base_time_offsets.dat");
      string str1;
      getline(INF,str1);
      double OFFSETS_OLD[2];
      INF>>OFFSETS_OLD[0]>>OFFSETS_OLD[1];
      INF.close();
      
      INF.open("adc_timing_offsets.dat");
      double ADCOFFSETS_OLD[176];
      getline(INF,str1);
      for (int k=0;k<176;k++){
	INF>>ADCOFFSETS_OLD[k];
      }
      INF.close();
      
      
      double OFFSETS_NEW[2];
      double ADCOFFSETS_NEW[176];
      
      char outf[128];
      sprintf(outf,"calibrations/base_time_offsets_NEWAMP_run%d.dat",RunNumber);
      ofstream OUTF(outf);
      OFFSETS_NEW[0] = OFFSETS_OLD[0]-GlobalTDCOffsetCorr;
      OFFSETS_NEW[1] = OFFSETS_OLD[1]-GlobalTDCOffsetCorr;
      OUTF<<"  "<<OFFSETS_NEW[0]<<"      "<<OFFSETS_NEW[1]<<endl;
      OUTF.close();
      
      sprintf(outf,"calibrations/adc_timing_offsets_NEWAMP_run%d.dat",RunNumber);
      OUTF.open(outf);
      for (int k=0;k<176;k++){
	ADCOFFSETS_NEW[k] =  ADCOFFSETS_OLD[k] + POS[k];
	OUTF<<"  "<<ADCOFFSETS_NEW[k]<<endl;
      }
      OUTF.close();
    }
}
